### ISSUE TITLE
Records Destructor

### ISSUE THREAD

**Issue by joeparkerz** [MahdiSafsafi/delphi-detours-library#23]
Hi!

How can this be written with DDetours. Now is made with BeaEngine.
I want to intercept Assign, Construct, Destruct of records and objects.

http://www.raysoftware.cn/wp-content/uploads/2014/09/Source.zip
http://www.raysoftware.cn/?p=518

**Comment by MahdiSafsafi** [comment]
Hi joeparkerz,
You can hook records methods the same way you do with class.
Here is a simple example:
```
var
  TrampolineOperator_Assign: procedure(const Self; const source: TTest) = nil;

procedure InterceptOperator_Assign(const Self; const source: TTest);
begin
  ShowMessage('Operator_Assign Hooked !');
  TrampolineOperator_Assign(Self, source);
end;

procedure TForm5.Button1Click(Sender: TObject);
var
  a: array [0 .. 1] of TTest;
begin
  a[0] := a[1];
end;

initialization

TrampolineOperator_Assign := InterceptCreate(@TTest.Operator_Assign, @InterceptOperator_Assign);
```
Please,for more information see the wiki page.

Mahdi.

**Comment by joeparkerz** [comment]
Hmm no this BeaEngine sourcecode hooks three things... 

HookProc(AddrOf_InitializeRecord(), @NewInitializeRecord, @OldInitializeRecord);
HookProc(AddrOf_FinalizeRecord(), @NewFinalizeRecord, @OldFinalizeRecord);
HookProc(AddrOf_CopyRecord(), @NewCopyRecord, @OldCopyRecord);

**Comment by MahdiSafsafi** [comment]
It's the same for the rest !!!
```
TrampolineOperator_Assign := InterceptCreate(@TTest.Operator_Assign, @InterceptOperator_Assign);
TrampolineOperator_Initialize := InterceptCreate(@TTest.Operator_Initialize, @InterceptOperator_Initialize);
TrampolineOperator_Finalize := InterceptCreate(@TTest.Operaor_Finalize, @InterceptOperaor_Finalize);
```

**Comment by joeparkerz** [comment]
No you don't understand please look at the code attached in the Source.zip
It allows hooking the methods in each record!

**Comment by MahdiSafsafi** [comment]
I don't understand what do you mean. Can you please give more details ?

**Comment by joeparkerz** [comment]
Please see this source code. http://pastebin.com/2nv9qSGm

How can it be modified to use your library. Not very easy!

**Comment by MahdiSafsafi** [comment]
Just replace HookProc by InterceptCreate and UnHook by InterceptRemove.
```
initialization

//HookProc(AddrOf_InitializeRecord(), @NewInitializeRecord, @OldInitializeRecord);
//HookProc(AddrOf_FinalizeRecord(), @NewFinalizeRecord, @OldFinalizeRecord);
//HookProc(AddrOf_CopyRecord(), @NewCopyRecord, @OldCopyRecord);

InterceptCreate(AddrOf_InitializeRecord(), @NewInitializeRecord, @OldInitializeRecord);
InterceptCreate(AddrOf_FinalizeRecord(), @NewFinalizeRecord, @OldFinalizeRecord);
InterceptCreate(AddrOf_CopyRecord(), @NewCopyRecord, @OldCopyRecord);

finalization

//UnHook(@OldInitializeRecord);
//UnHook(@OldFinalizeRecord);
//UnHook(@OldCopyRecord);

InterceptRemove(@OldInitializeRecord);
InterceptRemove(@OldFinalizeRecord);
InterceptRemove(@OldCopyRecord);
```
