### ISSUE TITLE
Compile with Lazarus/FPC

### ISSUE THREAD

**Issue by jamacoe** [MahdiSafsafi/delphi-detours-library#27]
The Readme.md mentions Lazarus/FPC support. Using the corresponding menu items from the Lazarus IDE, I converted the project and units of the DetoursDemo\win32api\Demo1 and tried to compile. But finally the compiler fails in CPUID.PAS: MOV EDI.TCPUIDStruct.rEAX,EAX (Error: Invalid reference syntax). How do I have to modify the code in order to compile it with Lazarus/FPC?

**Comment by MahdiSafsafi** [comment]
Hi jamacoe,
Only the first version (v1) that was tested on Lazarus/FPC and it works like a charm !
I didn't test v2 on FPC.
I didn't update the project from a while ... So it's going to take some time to be fixed. Once I find a free time I will take a deep look inside and try to fix this compatibility issue.

**Comment by VoittajaTomi** [comment]
Hi! What is the status of the compatibility now? In the Readme it says your lib is compatible with FPC, but the samples cannot be compiled? Could you please provide a working sample or a guide on how to use your library with Lazarus?

**Comment by MahdiSafsafi** [comment]
Hi @VoittajaTomi 
The current version does not support FPC. Only version 1 does !
For now, all what you can do is compiling it using Delphi as DLL and export functions to be used with FPC.
