### ISSUE TITLE
d2009 compatibility

### ISSUE THREAD

**Issue by Sorien** [MahdiSafsafi/delphi-detours-library#31]
delphi 2009 doesn't have RTTI lib and class constructor

**Comment by Sorien** [comment]
sorry don't have time to create PR, this modifications should make it working 
https://gist.github.com/Sorien/cb1b24126ac485d6f3ba

**Comment by MahdiSafsafi** [comment]
Hi Sorien,
Did you make the modification on the latest commit ?
PS: The latest commit was released today (one hour ago).

**Comment by Sorien** [comment]
https://github.com/MahdiSafsafi/delphi-detours-library/pull/32
