### ISSUE TITLE
InterceptCreate hooks Method behind interface but not the interface?

### ISSUE THREAD

**Issue by Memnarch** [MahdiSafsafi/delphi-detours-library#34]
I want to intercept an interface, without intercepting the method behind the interface.

for example the _AddRef method.

if i intercept the IInterface, calls to IInterface.AddReff and Self.AddRef will end up in my hooked method.

var
  LRef: IInterface;
  LFoo: TFoo;
begin
  LRef := TFoo as IInterface;
 InterCeptCreate(LRef._AddRef, 1, MyMethod);
 LRef._AddRef; <--endsup in my hook
LFoo._AddRef; <--endsup in my hook?
end;

is it possible to actually hook the IMT?

**Comment by MahdiSafsafi** [comment]
Hi Memnarch,
From what I understood, I think you are looking for patching the vtable.
Please try to use PatchVt/UnPatchVt functions (they are already declared in v2) and let me know.

Regards,
Mahdi

**Comment by Memnarch** [comment]
Thanks, i'll look into it!

**Comment by MahdiSafsafi** [comment]
Just let me know about your result so I can take a decision whether to close this issue or consider it as bug/feature-request.

**Comment by Memnarch** [comment]
YES! This worked. Thanky you very much.
