### ISSUE TITLE
Problem with access to field of object in trampolined method

### ISSUE THREAD

**Issue by jaclas** [MahdiSafsafi/delphi-detours-library#43]
Thanks to your tips I made a hook on the WndProc class TApplication. In my method I need to have access to my object's fields, but with this hook the context of the object changes and all fields are invalid. Can this be solved?
See screen from debug session:

![vps_2017 06 01_01](https://cloud.githubusercontent.com/assets/17312717/26670847/97c98be4-46b3-11e7-94b9-0713c784b521.png)

**Comment by jaclas** [comment]
I guess the reason is the hidden self pointing to the TApplication object, but how to bypass it?

**Comment by jaclas** [comment]
Ok, I found a some solution. Maybe a bit ugly but effective. I assign in MyWndProc method properly reference to internal self :-)

**Comment by MahdiSafsafi** [comment]
Hi jaclas,

The hooked method must live outside the class (must not be declared in TLogManager). If you declare it inside TLogManager, you must use an internal variable that holds TLogManager instance.
